name: CI

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
      - "renovate/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

env:
  RUSTFLAGS: "-D warnings"

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@v1
      - uses: Boshen/setup-rust@main
        with:
          save-cache: ${{ github.ref_name == 'main' }}
          components: clippy
      - run: cargo check
      - run: cargo clippy
      - run: RUSTDOCFLAGS='-D warnings' cargo doc --no-deps --document-private-items
